#==============================================#
# PropManager by RedSMURF: Configuration file #
#==============================================#

# To add a new prop, follow the example below
# [Prop Name]
# PROP_MODEL                    = Path of prop's model
# PROP_FLAGS                    = a - Solid         b - Anim

# PROP_SEQUENCE                 = Animation sequence for the prop model
# PROP_FRAMERATE                = Animation frame rate for the prop model
# PROP_SPAWN_CHANCE             = Prop's respawn probability (0.0 = never, 1.0 = always)
# PROP_MINS                     = Minimum bounding box of the prop (x y z)
# PROP_MAXS                     = Maximum bounding box of the prop (x y z)

# To make an prop available in the menu, you must defined at least it's name like this [Alien]
# prop model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/PropManager/6o4ka2.mdl
SETTING_DEFAULT_FLAGS           = a

SETTING_DEFAULT_FRAMERATE       = 1.0
SETTING_DEFAULT_SEQUENCE        = 0
SETTING_DEFAULT_SPAWN_CHANCE    = 1.0

SETTING_PROP_LOAD               = 1             # Whether to load saved props data of the current map
SETTING_PROP_RANGE              = 100.0         # Default range for prop interaction
SETTING_OFFSET_BASE             = 120.0         # Default forward offset when previewing prop placement
SETTING_OFFSET                  = 65.0 900.0    # Default minimum and maximum offset from the player to the prop (MIN MAX)
SETTING_OFFSET_STEP             = 10.0          # Step size when scrolling to move prop forward/backward
SETTING_OFFSET_FREQ             = 0.1           # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ              = 0.1           # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA             = 120           # Transparency level of the ghost preview model (0 - 255)

SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav

SETTING_COLOR_SELECT            = 0 255 0

; ===== BARRELS =====
[Barrel]
PROP_MODEL  = models/PropManager/6o4ka2.mdl
PROP_MINS   = -15 -15 0
PROP_MAXS   = 15 15 45

[Barrel Wood]
PROP_MODEL  = models/PropManager/AA_BarrelA_Wood_SMesh.mdl
PROP_MINS   = -30 -30 0
PROP_MAXS   = 30 30 87.5

; ===== CRATES & CONTAINERS =====
[Container]
PROP_MODEL  = models/PropManager/AF_container_close_new.mdl
PROP_MINS   = -155 -65 0
PROP_MAXS   = 155 65 135

[Tank]
PROP_MODEL  = models/PropManager/hl2_tank1.mdl
PROP_MINS   = -50 -160 -60
PROP_MAXS   = 50 160 60

[Crate]
PROP_MODEL  = models/PropManager/crate.mdl
PROP_MINS   = -50 -65 -2.5
PROP_MAXS   = 50 65 97.5

[Crate Large]
PROP_MODEL  = models/PropManager/crate2.mdl
PROP_MINS   = -20 -20 -20
PROP_MAXS   = 20 20 20

[Crate Down]
PROP_MODEL  = models/PropManager/cratedownc.mdl
PROP_MINS   = -16.5 -16 0
PROP_MAXS   = 16 16.5 32

[Crate Tarp]
PROP_MODEL  = models/PropManager/tarp_crate.mdl
PROP_MINS   = -27.5 -27.5 0
PROP_MAXS   = 27.5 27.5 105

[Chest]
PROP_MODEL  = models/PropManager/got_Chest02.mdl
PROP_MINS   = -17 -22 0
PROP_MAXS   = 17 22 27

[Chest Wooden]
PROP_MODEL  = models/PropManager/w_chest.mdl
PROP_MINS   = -13 -11 0
PROP_MAXS   = 15 9 20

; ===== NEON SIGNS / FOOD =====
[Burger]
PROP_MODEL  = models/PropManager/AF_big_burger.mdl
PROP_MINS   = -10 -10 0
PROP_MAXS   = 10 10 425

[Cafe Neon]
PROP_MODEL  = models/PropManager/AF_cafe_neon.mdl
PROP_MINS   = -5 -27 -32
PROP_MAXS   = 5 20 32

[Pizza]
PROP_MODEL  = models/PropManager/AF_neon_pizza.mdl
PROP_MINS   = -1 -15 -10
PROP_MAXS   = 1 15 10
PROP_FLAGS  = 0

[Hotel Neon]
PROP_MODEL  = models/PropManager/zps_hotel_neon.mdl
PROP_MINS   = -20 -7 0
PROP_MAXS   = 20 7 145.5

; ===== SIGNS =====
[Diner Sign]
PROP_MODEL  = models/PropManager/diner_sign.mdl
PROP_MINS   = -142 -15 0
PROP_MAXS   = 114 29 52

[Exit Sign]
PROP_MODEL  = models/PropManager/exit_sign.mdl
PROP_MINS   = -15 -5 -6
PROP_MAXS   = 15 5 10.5

[Exit Wall]
PROP_MODEL  = models/PropManager/Exit_wall.mdl
PROP_MINS   = -22 -3 -6.5
PROP_MAXS   = 0 3 6.5

[Park Sign]
PROP_MODEL  = models/PropManager/parksign.mdl
PROP_MINS   = -15 0 0
PROP_MAXS   = 15 77.5 165

[Sign Cone]
PROP_MODEL  = models/PropManager/sign_cone.mdl
PROP_MINS   = -21 -21 0
PROP_MAXS   = 21 21 100

[Shop Sign]
PROP_MODEL  = models/PropManager/signs_shops02_a.mdl
PROP_MINS   = -12 -1 -14
PROP_MAXS   = 12 1 0

[Speed Sign]
PROP_MODEL  = models/PropManager/Speed_Sign.mdl
PROP_MINS   = -1 -1 0
PROP_MAXS   = 1 1 90

[Stop Sign]
PROP_MODEL  = models/PropManager/Stop_Sign.mdl
PROP_MINS   = -1 -1 0
PROP_MAXS   = 1 1 85

; ===== FENCES & BARRICADES =====
[Barricade]
PROP_MODEL  = models/PropManager/barricade02.mdl
PROP_MINS   = -5 -35 -32
PROP_MAXS   = 0 35 32

[Fence COD4]
PROP_MODEL  = models/PropManager/fence_cod4_01.mdl
PROP_MINS   = -2.5 -37 -12.5
PROP_MAXS   = 2.5 38 27

[Fence Metal]
PROP_MODEL  = models/PropManager/metal_fence2.mdl
PROP_MINS   = -5 -57.5 0
PROP_MAXS   = 5 53.5 95

[Fence Village]
PROP_MODEL  = models/PropManager/mex_fence_willage02.mdl
PROP_MINS   = -87.5 -10 0
PROP_MAXS   = 87.5 10 95

; ===== FURNITURE =====
[Bench Outdoor]
PROP_MODEL  = models/PropManager/BenchOutdoor01a.mdl
PROP_MINS   = -50 -12.5 -12
PROP_MAXS   = 50 12.5 7.5

[Prison Bed]
PROP_MODEL  = models/PropManager/got_Prison_Bed01.mdl
PROP_MINS   = 0 -42 0
PROP_MAXS   = 25 38 3

; ===== DECOR / MISC =====
[Statue Paque]
PROP_MODEL  = models/PropManager/D1_SM_StatueIlePaque.mdl
PROP_MINS   = -100 -100 0
PROP_MAXS   = 100 80 500

[Stone Dog]
PROP_MODEL  = models/PropManager/dao_stonedog.mdl
PROP_MINS   = -9 -4 0
PROP_MAXS   = 9 24 40

[Gnome]
PROP_MODEL  = models/PropManager/gnome_optimize.mdl
PROP_MINS   = -6.5 -5 0
PROP_MAXS   = 7 5 25

[Farm Light]
PROP_MODEL  = models/PropManager/svetafarmalink.mdl
PROP_MINS   = -5 0 0
PROP_MAXS   = 5 10 100











